apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-client
  template:
    metadata:
      labels:
        app: dummy-client
    spec:
      containers:
        - name: dummy-client
          image: shobhit3718/dummy-client:latest
          args: ["13.203.156.239","30000", "--bot"]
          env:
            - name: BOT_FILE_SIZE_MULTIPLIER
              value: "1"
